### ISSUE TITLE
Add Markdown example

### ISSUE THREAD

**Issue by sake92** [sake92/hepek-examples#4]
This one is piece of cake. There is support for Commonmark flavored markdown in Hepek.  
Examples should be clear and simple. E.g. showing how to bold text, italic, code snippet, bullets, numberings, newline etc.

Feel free to ask questions if something isn't clear. 🙂

**Comment by jerdog** [comment]
I'll take this one - where do you anticipate having this? As its own thing or in a specific README file?

**Comment by sake92** [comment]
@jerdog It needs to be an example like these [here](https://github.com/sake92/hepek-examples/tree/master/src/main/scala/examples).  
Make a folder `markdown` and in it a file `MarkdownExample.scala`.  
It should extend [`StaticPage`](https://github.com/sake92/hepek/blob/master/src/main/scala/ba/sake/hepek/html/structure/StaticPage.scala) and [`BasicComponents`](https://github.com/sake92/hepek/blob/master/src/main/scala/ba/sake/hepek/html/component/BasicComponents.scala).

Just override `pageContent` and you're ready to go! 🙂  
See this example for help: https://github.com/sake92/hepek-starter/blob/master/src/main/scala/site/About.scala

**Comment by jerdog** [comment]
Got it - ok. I will let someone else take, but it's good to understand what it is you're wanting help with.

**Comment by Mera-Gangapersaud** [comment]
I would like to work on this.

**Comment by sake92** [comment]
@Mera-Gangapersaud let me know if you need any help! 😉
